### ISSUE TITLE
smooth_lowess_bootstrap

### ISSUE THREAD

**Issue by hcgoldbach** [histed/PyToolsMH#5]
@histed 

Trying to run ptMH.math.smooth_lowess_bootstrap 

Getting an error re: "x must be strictly increasing". 
I introduced some jitter to the x-values to make sure they wouldn't overlap and then sorted the whole data-frame by x-value. This works fine for ptMH.math.smooth_lowess. 

I just pushed an example notebook to git under analysisBehavior2016/191028-HVAanalysis/develop/201123-HG-lowess_bootstrap
<img width="999" alt="Screen Shot 2020-11-24 at 12 14 56 AM" src="https://user-images.githubusercontent.com/22198490/100051521-17cf7080-2dea-11eb-8bb4-176e0b78e73e.png">

**Comment by histed** [comment]
I got a different error due to indexing, and I fixed it:
![image](https://user-images.githubusercontent.com/176407/100113367-3d866500-2e3e-11eb-853c-98e1cd6fc489.png)

**Comment by histed** [comment]
I'm using this version of PytoolsMH:
![image](https://user-images.githubusercontent.com/176407/100113476-598a0680-2e3e-11eb-960a-a2c810e4e156.png)

**Comment by histed** [comment]
You may need to upgrade PytoolsMH.  Here is how:

    conda activate mh37e
    cd ~/Repositories/PytoolsMH
    git pull 
    python setup.py develop

**Comment by histed** [comment]
Pushing the notebook back to git.  If you still have problems, please reopen.
