### ISSUE TITLE
smooth_lowess has incorrect assertion

### ISSUE THREAD

**Issue by lafosse** [histed/PyToolsMH#6]
In math.py smooth_lowess() function, there is a check for the number of data points to smooth across:
```
y = a_(y, dtype='f8')
nPts = y.shape[axis]

if len(y) < 2:
     raise ValueError('Input must have length > 1')
```
In the above code snippet, I believe the condition for the assertion should read 
```
if nPts < 2:
     raise ...
```
Currently, if I pass in an array of shape [1,N] and specify the axis as 1 in the smooth_lowess input variable (i.e. to smooth across N data points), this assertion gets triggered even though it is a valid array with a correctly specified axis to smooth across.

**Comment by histed** [comment]
That looks like the correct fix — feel free to pull request.
