### ISSUE TITLE
smooth_lowess_bootstrap input variable defaults to None but is still needed in funciton

### ISSUE THREAD

**Issue by lafosse** [histed/PyToolsMH#8]
<img width="1208" alt="Screen Shot 2021-12-20 at 11 43 12 PM" src="https://user-images.githubusercontent.com/20845134/146951596-6815c011-8907-4c8c-a854-c4c5efa49cca.png">

the variable x is set to default to None when no input is passed, but the code uses the min and max of this variable, so it throws an error.

**Comment by histed** [comment]
Testcase in analysisImaging2021/211216-PKL-2p+vis-ampsup/develop/
